version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 701150702050.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo Get env configs
      - |
        cat > staging.env <<EOF
        APP_NAME=Laravel
        APP_ENV=local
        APP_KEY=base64:lIG2TxH/rAVb019PKu1/CQjDcAcLo3KrLxLqp1DsS6Y=
        APP_DEBUG=true
        APP_LOG_LEVEL=debug
        APP_URL=http://localhost

        DB_CONNECTION=mysql
        DB_HOST=127.0.0.1
        DB_PORT=3306
        DB_DATABASE=homestead
        DB_USERNAME=homestead
        DB_PASSWORD=secret

        BROADCAST_DRIVER=log
        CACHE_DRIVER=file
        SESSION_DRIVER=file
        SESSION_LIFETIME=120
        QUEUE_DRIVER=sync

        REDIS_HOST=127.0.0.1
        REDIS_PASSWORD=null
        REDIS_PORT=6379

        MAIL_DRIVER=smtp
        MAIL_HOST=smtp.mailtrap.io
        MAIL_PORT=2525
        MAIL_USERNAME=null
        MAIL_PASSWORD=null
        MAIL_ENCRYPTION=null

        PUSHER_APP_ID=
        PUSHER_APP_KEY=
        PUSHER_APP_SECRET=
        PUSHER_APP_CLUSTER=mt1

        LINE_CHANNEL_ID=
        LINE_CHANNEL_SECRET=
        LINE_REDIRECT=
        LINE_BOT_CHANNEL_ACCESS_TOKEN=
        LINE_BOT_CHANNEL_SECRET=

        TEST_ENV=tangbo
        EOF
      - echo Build started on `date`
      - echo Building the Docker image...
      - |
        docker run \
          --env-file staging.env \
          -v "$(pwd)":/app \
          -e STACK=heroku-22 \
          701150702050.dkr.ecr.ap-northeast-1.amazonaws.com/heroku:22-build \
          sh -c "git clone https://github.com/heroku/heroku-buildpack-php /tmp/buildpack && /tmp/buildpack/bin/compile /app /tmp/cache"
      - |
        tagname=701150702050.dkr.ecr.ap-northeast-1.amazonaws.com/pipeline-build-demo:$(date -u '+%Y%m%d.%H%M%S')
        docker build -t $tagname .
        docker push $tagname
      - echo Build Done
