version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 701150702050.dkr.ecr.ap-northeast-1.amazonaws.com
      - echo Get AppConfigData
      - |
        aws appconfigdata get-latest-configuration \
          --configuration-token \
            $(aws appconfigdata start-configuration-session \
            --application-identifier lak \
            --environment-identifier production \
            --configuration-profile-identifier main --no-cli-pager --output text) \
          --no-cli-pager \
          .env \
          > /dev/null 2>&1
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - |
        docker run \
          --env-file .env \
          -v "$(pwd)":/app \
          -e STACK=heroku-22 \
          701150702050.dkr.ecr.ap-northeast-1.amazonaws.com/heroku:22-build \
          sh -c "git clone https://github.com/heroku/heroku-buildpack-php /tmp/buildpack && /tmp/buildpack/bin/compile /app /tmp/cache"
      - |
        tagname=701150702050.dkr.ecr.ap-northeast-1.amazonaws.com/pipeline-build-demo:$(date -u '+%Y%m%d.%H%M%S')
        docker build -t $tagname .
        docker push $tagname
      - echo Build Done
